import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { NamiButton } from "../shared/components/nami-button.client";
import { Button } from "../shared/components/button";

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cardano.webp" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Full-Stack <a href="https://cardano.org">Cardano</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <NamiButton />
          <Button text={'Register'} className={`${styles.button} ${styles.bg_green}`}/>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://cardano.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/cardano-logo.webp" alt="Cardano Logo" width={200} height={40} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
